version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql-data:/var/lib/mysql  # Добавляем volume для данных
    command: --default-authentication-plugin=mysql_native_password

  sut:
    image: openjdk:11
    container_name: app-sut
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/app
      DB_USER: app
      DB_PASS: pass
    ports:
      - "9999:9999"
    volumes:
      - ./artifacts/app-deadline.jar:/app/app-deadline.jar
    working_dir: /app
    command: ["java", "-jar", "app-deadline.jar"]

volumes:
  mysql-data: