version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password --ssl-mode=DISABLED

  sut:
    image: openjdk:11
    container_name: app-sut
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql-db:3306/app?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      DB_USER: app
      DB_PASS: pass
    ports:
      - "9999:9999"
    volumes:
      - ./artifacts/app-deadline.jar:/app/app-deadline.jar
    working_dir: /app
    command: >
      bash -c "
        echo 'Waiting for MySQL...' &&
        sleep 30 &&
        java -jar app-deadline.jar
      "