version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  sut:
    image: openjdk:11
    container_name: app-sut
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/app?serverTimezone=UTC
      DB_USER: app
      DB_PASS: pass
    ports:
      - "9999:9999"
    volumes:
      - ./artifacts/app-deadline.jar:/app/app-deadline.jar
    working_dir: /app
    command: ["java", "-jar", "app-deadline.jar"]